"""create_pet_model-10

Revision ID: f7a608ab0cd5
Revises: ca7d0f75bfa3
Create Date: 2024-01-24 21:50:37.544004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7a608ab0cd5"
down_revision = "ca7d0f75bfa3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
