"""create_pet_model-7

Revision ID: b23ec0311931
Revises: b1fcd9927e34
Create Date: 2024-01-24 21:46:04.794654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b23ec0311931"
down_revision = "b1fcd9927e34"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
