"""pet-v2

Revision ID: 9ff7f5226b43
Revises: 01afa1f280c9
Create Date: 2024-01-22 22:43:02.632094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ff7f5226b43"
down_revision = "01afa1f280c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("BSP", sa.String(length=250), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website", sa.String(length=250), nullable=True),
        sa.Column("email", sa.String(length=250), nullable=True),
        sa.Column("road", sa.String(length=254), nullable=True),
        sa.Column("city", sa.String(length=254), nullable=True),
        sa.Column("state", sa.String(length=254), nullable=True),
        sa.Column("zip", sa.String(length=254), nullable=True),
        sa.Column("country", sa.String(length=254), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "staff",
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "specialisation",
            sa.Enum(
                "Canine_Medicine",
                "Feline_Medicine",
                "Equine_Medicine",
                "Avian_Medicine",
                "Exotic_Animal_Medicine",
                "Dental_Specialist",
                "Orthopedic_Surgeon",
                "Ophthalmologist",
                "Dermatologist",
                "Behavioral_Specialist",
                "Radiology",
                "Nutritionist",
                "Emergency_and_Critical_Care",
                "Internal_Medicine",
                "Surgery",
                "Anesthesiology",
                "Pathology",
                "Rehabilitation_Therapist",
                "Public_Health",
                "Zoological_Medicine",
                "Other",
                name="specialisationtype",
            ),
            nullable=True,
        ),
        sa.Column("first_name", sa.String(length=254), nullable=True),
        sa.Column("last_name", sa.String(length=254), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("mobile_number", sa.String(length=20), nullable=True),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("road", sa.String(length=254), nullable=True),
        sa.Column("city", sa.String(length=254), nullable=True),
        sa.Column("state", sa.String(length=254), nullable=True),
        sa.Column("zip", sa.String(length=254), nullable=True),
        sa.Column("country", sa.String(length=254), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_staff_email"), "staff", ["email"], unique=True)
    op.create_table(
        "animal_weight_history",
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("change_date", sa.DateTime(), nullable=False),
        sa.Column("animal_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["animal_id"],
            ["animal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clinic",
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("email", sa.String(length=250), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website", sa.String(length=250), nullable=True),
        sa.Column(
            "specialisation",
            sa.Enum(
                "Canine_Medicine",
                "Feline_Medicine",
                "Equine_Medicine",
                "Avian_Medicine",
                "Exotic_Animal_Medicine",
                "Dental_Specialist",
                "Orthopedic_Surgeon",
                "Ophthalmologist",
                "Dermatologist",
                "Behavioral_Specialist",
                "Radiology",
                "Nutritionist",
                "Emergency_and_Critical_Care",
                "Internal_Medicine",
                "Surgery",
                "Anesthesiology",
                "Pathology",
                "Rehabilitation_Therapist",
                "Public_Health",
                "Zoological_Medicine",
                "Other",
                name="specialisationtype",
            ),
            nullable=True,
        ),
        sa.Column(
            "animal_types",
            sa.Enum(
                "Dog",
                "Cat",
                "Horse",
                "Bird",
                "Rabbit",
                "Rodent",
                "Reptile",
                "Amphibian",
                "Fish",
                "Ferret",
                "Guinea Pig",
                "Hamster",
                "Exotic Mammal",
                "Farm/Livestock",
                "Other",
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("road", sa.String(length=254), nullable=True),
        sa.Column("city", sa.String(length=254), nullable=True),
        sa.Column("state", sa.String(length=254), nullable=True),
        sa.Column("zip", sa.String(length=254), nullable=True),
        sa.Column("country", sa.String(length=254), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "staff_clinic",
        sa.Column("staff_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("clinic_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "Veterinarian",
                "Veterinary_Technician",
                "Receptionist",
                "Groomer",
                "Animal_Care_Assistant",
                "Laboratory_Technician",
                "Administrative_Staff",
                "Emergency_Response_Team",
                "Specialist",
                "Intern",
                "Other",
                name="roletype",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["clinic_id"],
            ["clinic.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedule",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("opening_time", sa.Time(), nullable=False),
        sa.Column("closing_time", sa.Time(), nullable=False),
        sa.Column("staff_clinic_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["staff_clinic_id"],
            ["staff_clinic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "appointment",
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("schedule_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("appointment_time", sa.DateTime(), nullable=False),
        sa.Column("activity_duration", sa.Interval(), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedule.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "animal_log",
        sa.Column("animal_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("appointment_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column(
            "activity",
            sa.Enum(
                "check-up",
                "operation",
                "sale",
                "vaccination",
                "dental",
                "grooming",
                "emergency",
                "consultation",
                "imaging",
                "other",
                "phone",
                "Bath",
                "Feces",
                "Injury",
                "Exercise",
                "Food",
                "Nails",
                "Wash",
                "Urine",
                "Vomit",
                "Deworming",
                "Water",
                "Sleep",
                "Seizure",
                "Season",
                "Medication",
                name="activity_types",
            ),
            nullable=False,
        ),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("procedures", sa.Text(), nullable=True),
        sa.Column("medication", sa.Text(), nullable=True),
        sa.Column("food_name", sa.Text(), nullable=True),
        sa.Column("medication_brand", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["animal_id"],
            ["animal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "animal",
        sa.Column(
            "animal_types",
            sa.Enum(
                "Dog",
                "Cat",
                "Horse",
                "Bird",
                "Rabbit",
                "Rodent",
                "Reptile",
                "Amphibian",
                "Fish",
                "Ferret",
                "Guinea Pig",
                "Hamster",
                "Exotic Mammal",
                "Farm/Livestock",
                "Other",
            ),
            nullable=False,
        ),
    )
    op.add_column("animal", sa.Column("date_of_birth", sa.Date(), nullable=False))
    op.add_column("animal", sa.Column("date_of_death", sa.Date(), nullable=True))
    op.add_column("animal", sa.Column("active", sa.Boolean(), nullable=False))
    op.add_column(
        "animal", sa.Column("phone_number", sa.String(length=20), nullable=False)
    )
    op.add_column("animal", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("animal", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("animal", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.add_column("animal", sa.Column("version", sa.Integer(), nullable=True))
    op.alter_column(
        "animal",
        "height",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.drop_column("animal", "weight")
    op.drop_column("animal", "same_address_as_owner")
    op.drop_column("animal", "type")
    op.drop_column("animal", "age")
    op.add_column(
        "animal_user_association",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
    )
    op.add_column(
        "animal_user_association", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "animal_user_association", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "animal_user_association", sa.Column("is_deleted", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "animal_user_association", sa.Column("version", sa.Integer(), nullable=True)
    )
    op.add_column(
        "user_model", sa.Column("first_name", sa.String(length=254), nullable=True)
    )
    op.add_column(
        "user_model", sa.Column("last_name", sa.String(length=254), nullable=True)
    )
    op.add_column(
        "user_model", sa.Column("mobile_number", sa.String(length=20), nullable=True)
    )
    op.add_column("user_model", sa.Column("active", sa.Boolean(), nullable=False))
    op.add_column("user_model", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("user_model", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("user_model", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.add_column("user_model", sa.Column("version", sa.Integer(), nullable=True))
    op.alter_column(
        "user_model",
        "phone_number",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=20),
        nullable=False,
    )
    op.drop_column("user_model", "name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_model",
        sa.Column("name", sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "user_model",
        "phone_number",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=128),
        nullable=True,
    )
    op.drop_column("user_model", "version")
    op.drop_column("user_model", "is_deleted")
    op.drop_column("user_model", "updated_at")
    op.drop_column("user_model", "created_at")
    op.drop_column("user_model", "active")
    op.drop_column("user_model", "mobile_number")
    op.drop_column("user_model", "last_name")
    op.drop_column("user_model", "first_name")
    op.drop_column("animal_user_association", "version")
    op.drop_column("animal_user_association", "is_deleted")
    op.drop_column("animal_user_association", "updated_at")
    op.drop_column("animal_user_association", "created_at")
    op.drop_column("animal_user_association", "id")
    op.add_column(
        "animal",
        sa.Column("age", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    )
    op.add_column(
        "animal",
        sa.Column("type", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    )
    op.add_column(
        "animal",
        sa.Column(
            "same_address_as_owner", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "animal",
        sa.Column("weight", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "animal",
        "height",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    op.drop_column("animal", "version")
    op.drop_column("animal", "is_deleted")
    op.drop_column("animal", "updated_at")
    op.drop_column("animal", "created_at")
    op.drop_column("animal", "phone_number")
    op.drop_column("animal", "active")
    op.drop_column("animal", "date_of_death")
    op.drop_column("animal", "date_of_birth")
    op.drop_column("animal", "animal_types")
    op.drop_table("animal_log")
    op.drop_table("appointment")
    op.drop_table("schedule")
    op.drop_table("staff_clinic")
    op.drop_table("clinic")
    op.drop_table("animal_weight_history")
    op.drop_index(op.f("ix_staff_email"), table_name="staff")
    op.drop_table("staff")
    op.drop_table("organization")
    # ### end Alembic commands ###
