"""create_pet_model22

Revision ID: 01afa1f280c9
Revises: f88679e5001b
Create Date: 2024-01-19 16:47:43.156513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "01afa1f280c9"
down_revision = "f88679e5001b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
