"""create_pet_model-3

Revision ID: ce65e2d4a74c
Revises: 0d7ee2cb139a
Create Date: 2024-01-24 20:44:12.034218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ce65e2d4a74c"
down_revision = "0d7ee2cb139a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
