"""create_pet_model-8

Revision ID: 96727b8e407a
Revises: b23ec0311931
Create Date: 2024-01-24 21:46:18.823178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96727b8e407a"
down_revision = "b23ec0311931"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
