"""create_pet_model

Revision ID: f88679e5001b
Revises: 07c71f4389b6
Create Date: 2024-01-17 22:17:13.170325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f88679e5001b"
down_revision = "07c71f4389b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "animal",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("identifier", sa.String(length=254), nullable=True),
        sa.Column("name", sa.String(length=254), nullable=True),
        sa.Column("age", sa.String(length=128), nullable=True),
        sa.Column("sex", sa.String(length=50), nullable=True),
        sa.Column("weight", sa.String(length=128), nullable=True),
        sa.Column("height", sa.String(length=128), nullable=True),
        sa.Column("type", sa.String(length=128), nullable=False),
        sa.Column("color", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=128), nullable=True),
        sa.Column("image", sa.String(length=128), nullable=True),
        sa.Column("same_address_as_owner", sa.Boolean(), nullable=True),
        sa.Column("road", sa.String(length=254), nullable=True),
        sa.Column("city", sa.String(length=254), nullable=True),
        sa.Column("state", sa.String(length=254), nullable=True),
        sa.Column("zip", sa.String(length=254), nullable=True),
        sa.Column("country", sa.String(length=254), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "animal_user_association",
        sa.Column("animal_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=True),
        sa.ForeignKeyConstraint(
            ["animal_id"],
            ["animal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_model.id"],
        ),
    )
    op.add_column("user_model", sa.Column("name", sa.String(length=254), nullable=True))
    op.add_column(
        "user_model", sa.Column("phone_number", sa.String(length=128), nullable=True)
    )
    op.add_column("user_model", sa.Column("road", sa.String(length=254), nullable=True))
    op.add_column("user_model", sa.Column("city", sa.String(length=254), nullable=True))
    op.add_column(
        "user_model", sa.Column("state", sa.String(length=254), nullable=True)
    )
    op.add_column("user_model", sa.Column("zip", sa.String(length=254), nullable=True))
    op.add_column(
        "user_model", sa.Column("country", sa.String(length=254), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_model", "country")
    op.drop_column("user_model", "zip")
    op.drop_column("user_model", "state")
    op.drop_column("user_model", "city")
    op.drop_column("user_model", "road")
    op.drop_column("user_model", "phone_number")
    op.drop_column("user_model", "name")
    op.drop_table("animal_user_association")
    op.drop_table("animal")
    # ### end Alembic commands ###
