"""create_pet_modelbrands-clean

Revision ID: 90e486ad8bbb
Revises: 84caa38f4010
Create Date: 2024-01-23 18:43:17.138267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90e486ad8bbb"
down_revision = "84caa38f4010"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
