"""create_pet_model-2

Revision ID: aa89b43d622c
Revises: 6b4a6d5be983
Create Date: 2024-01-25 10:30:04.003039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aa89b43d622c"
down_revision = "6b4a6d5be983"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("appointment_user_id_fkey", "appointment", type_="foreignkey")
    op.create_foreign_key(
        None, "appointment", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "appointment", type_="foreignkey")
    op.create_foreign_key(
        "appointment_user_id_fkey", "appointment", "user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
