"""create_pet_model-4

Revision ID: 34d6162bae8c
Revises: 7d83e4dc11a9
Create Date: 2024-01-25 16:27:03.832759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "34d6162bae8c"
down_revision = "7d83e4dc11a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "animal_log_appointment_id_fkey", "animal_log", type_="foreignkey"
    )
    op.drop_constraint("animal_log_animal_id_fkey", "animal_log", type_="foreignkey")
    op.create_foreign_key(
        None, "animal_log", "animal", ["animal_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "animal_log",
        "appointment",
        ["appointment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "animal_log", type_="foreignkey")
    op.drop_constraint(None, "animal_log", type_="foreignkey")
    op.create_foreign_key(
        "animal_log_animal_id_fkey", "animal_log", "animal", ["animal_id"], ["id"]
    )
    op.create_foreign_key(
        "animal_log_appointment_id_fkey",
        "animal_log",
        "appointment",
        ["appointment_id"],
        ["id"],
    )
    # ### end Alembic commands ###
