"""create_pet_model-5

Revision ID: b1fcd9927e34
Revises: e4710149cbc5
Create Date: 2024-01-24 21:30:47.901906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b1fcd9927e34"
down_revision = "e4710149cbc5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
