"""create_pet_model-4

Revision ID: e4710149cbc5
Revises: ce65e2d4a74c
Create Date: 2024-01-24 20:47:51.511823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e4710149cbc5"
down_revision = "ce65e2d4a74c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
