"""create_pet_model-9

Revision ID: ca7d0f75bfa3
Revises: 96727b8e407a
Create Date: 2024-01-24 21:50:05.938809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca7d0f75bfa3"
down_revision = "96727b8e407a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
