"""create_pet_model-3

Revision ID: 7d83e4dc11a9
Revises: aa89b43d622c
Create Date: 2024-01-25 15:28:01.079163

"""
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = "7d83e4dc11a9"
down_revision = "aa89b43d622c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "activitytypes",
        [
            "all",
            "check_up",
            "operation",
            "sale",
            "vaccination",
            "dental",
            "grooming",
            "emergency",
            "consultation",
            "imaging",
            "other",
            "phone",
            "Bath",
            "Feces",
            "Injury",
            "Exercise",
            "Food",
            "Nails",
            "Wash",
            "Urine",
            "Vomit",
            "Deworming",
            "Water",
            "Sleep",
            "Seizure",
            "Season",
            "Medication",
        ],
        [TableReference("animal_log", "activity")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "activitytypes",
        [
            "check_up",
            "operation",
            "sale",
            "vaccination",
            "dental",
            "grooming",
            "emergency",
            "consultation",
            "imaging",
            "other",
            "phone",
            "Bath",
            "Feces",
            "Injury",
            "Exercise",
            "Food",
            "Nails",
            "Wash",
            "Urine",
            "Vomit",
            "Deworming",
            "Water",
            "Sleep",
            "Seizure",
            "Season",
            "Medication",
        ],
        [TableReference("animal_log", "activity")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
